---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: group-7
  labels:
    app: api
    owner: group-7
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{ .Values.imageRegistry }}:{{ .Values.dockerTag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1500Mi"
            cpu: "250m"
          limits:
            memory: "3000Mi"
            cpu: "400m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-container-envs
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-connection-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-connection-secrets
                key: password
          - name: DB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: db-connection-secrets
                key: endpoint
          - name: DB_NAME
            valueFrom:
             secretKeyRef:
                name: db-connection-secrets
                key: api_db_name
          - name: DATABASE_URL
            value: "postgresql+psycopg2://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_ENDPOINT)/$(DB_NAME)"

