---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer
  labels:
    owner: group-7
spec:
  selector:
    app: api
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

